version: '3.9'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:  
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ["npm", "run", "dev", "--", "--host"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  db:
    image: postgres:13
    env_file:  # Load environment variables for PostgreSQL
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
